import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to my Next.js Pokedex!</h1>

        <p className={styles.description}>
          Get started by{" "}
          <Link href="/pokedex">
            <a>looking for a Pokémon</a>
          </Link>
        </p>
      </main>

      <footer className={styles.footer}>
        <p>© Bryan Florestal 2022, All rights reserved</p>
      </footer>
    </div>
  );
}
